openapi: 3.1.0
info:
  title: IgniteGPT Persistence API
  description: An API for interacting with LLMs
  version: 0.1.0
servers:
  - url: https://api.ignitegpt.com/rest/v1
paths:
  /trees:
    $ref: './postgrest.yaml#/paths/~1trees'
  /messages:
    $ref: './postgrest.yaml#/paths/~1messages'
components:
  $ref: './postgrest.yaml#/components'
