openapi: 3.1.0
info:
  title: IgniteGPT Persistence API
  description: An API for interacting with LLMs
  version: 0.1.0
servers:
  - url: https://api.ignitegpt.com/v1
paths:
  $ref: './paths.yaml'
components:
  schemas:
    $ref: './schemas.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
