openapi: 3.0.0
info:
  description: standard public schema
  title: PostgREST API
  version: 10.2.0 (e07807d)
paths:
  /:
    get:
      tags:
        - Introspection
      summary: OpenAPI description (this document)
      responses:
        "200":
          description: OK
  /trees:
    get:
      tags:
        - trees
      parameters:
        - $ref: "#/components/parameters/rowFilter.trees.id"
        - $ref: "#/components/parameters/rowFilter.trees.name"
        - $ref: "#/components/parameters/rowFilter.trees.description"
        - $ref: "#/components/parameters/rowFilter.trees.userId"
        - $ref: "#/components/parameters/rowFilter.trees.forks"
        - $ref: "#/components/parameters/rowFilter.trees.isPublic"
        - $ref: "#/components/parameters/rowFilter.trees.createdAt"
        - $ref: "#/components/parameters/rowFilter.trees.updatedAt"
        - $ref: "#/components/parameters/rowFilter.trees.forkSourceId"
        - $ref: "#/components/parameters/rowFilter.trees.settings"
        - $ref: "#/components/parameters/rowFilter.trees.isTemplate"
        - $ref: "#/components/parameters/rowFilter.trees.templateId"
        - $ref: "#/components/parameters/select"
        - $ref: "#/components/parameters/order"
        - $ref: "#/components/parameters/range"
        - $ref: "#/components/parameters/rangeUnit"
        - $ref: "#/components/parameters/offset"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/preferCount"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/trees"
                type: array
            application/vnd.pgrst.object+json:
              schema:
                items:
                  $ref: "#/components/schemas/trees"
                type: array
            text/csv:
              schema:
                items:
                  $ref: "#/components/schemas/trees"
                type: array
        "206":
          description: Partial Content
    post:
      tags:
        - trees
      parameters:
        - $ref: "#/components/parameters/select"
        - $ref: "#/components/parameters/preferPost"
      requestBody:
        $ref: "#/components/requestBodies/trees"
      responses:
        "201":
          description: Created
    delete:
      tags:
        - trees
      parameters:
        - $ref: "#/components/parameters/rowFilter.trees.id"
        - $ref: "#/components/parameters/rowFilter.trees.name"
        - $ref: "#/components/parameters/rowFilter.trees.description"
        - $ref: "#/components/parameters/rowFilter.trees.userId"
        - $ref: "#/components/parameters/rowFilter.trees.forks"
        - $ref: "#/components/parameters/rowFilter.trees.isPublic"
        - $ref: "#/components/parameters/rowFilter.trees.createdAt"
        - $ref: "#/components/parameters/rowFilter.trees.updatedAt"
        - $ref: "#/components/parameters/rowFilter.trees.forkSourceId"
        - $ref: "#/components/parameters/rowFilter.trees.settings"
        - $ref: "#/components/parameters/rowFilter.trees.isTemplate"
        - $ref: "#/components/parameters/rowFilter.trees.templateId"
        - $ref: "#/components/parameters/preferReturn"
      responses:
        "204":
          description: No Content
    patch:
      tags:
        - trees
      parameters:
        - $ref: "#/components/parameters/rowFilter.trees.id"
        - $ref: "#/components/parameters/rowFilter.trees.name"
        - $ref: "#/components/parameters/rowFilter.trees.description"
        - $ref: "#/components/parameters/rowFilter.trees.userId"
        - $ref: "#/components/parameters/rowFilter.trees.forks"
        - $ref: "#/components/parameters/rowFilter.trees.isPublic"
        - $ref: "#/components/parameters/rowFilter.trees.createdAt"
        - $ref: "#/components/parameters/rowFilter.trees.updatedAt"
        - $ref: "#/components/parameters/rowFilter.trees.forkSourceId"
        - $ref: "#/components/parameters/rowFilter.trees.settings"
        - $ref: "#/components/parameters/rowFilter.trees.isTemplate"
        - $ref: "#/components/parameters/rowFilter.trees.templateId"
        - $ref: "#/components/parameters/preferReturn"
      requestBody:
        $ref: "#/components/requestBodies/trees"
      responses:
        "204":
          description: No Content
  /messages:
    get:
      tags:
        - messages
      parameters:
        - $ref: "#/components/parameters/rowFilter.messages.id"
        - $ref: "#/components/parameters/rowFilter.messages.treeId"
        - $ref: "#/components/parameters/rowFilter.messages.parent"
        - $ref: "#/components/parameters/rowFilter.messages.content"
        - $ref: "#/components/parameters/rowFilter.messages.role"
        - $ref: "#/components/parameters/rowFilter.messages.createdAt"
        - $ref: "#/components/parameters/rowFilter.messages.updatedAt"
        - $ref: "#/components/parameters/rowFilter.messages.comment"
        - $ref: "#/components/parameters/select"
        - $ref: "#/components/parameters/order"
        - $ref: "#/components/parameters/range"
        - $ref: "#/components/parameters/rangeUnit"
        - $ref: "#/components/parameters/offset"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/preferCount"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/messages"
                type: array
            application/vnd.pgrst.object+json:
              schema:
                items:
                  $ref: "#/components/schemas/messages"
                type: array
            text/csv:
              schema:
                items:
                  $ref: "#/components/schemas/messages"
                type: array
        "206":
          description: Partial Content
    post:
      tags:
        - messages
      parameters:
        - $ref: "#/components/parameters/select"
        - $ref: "#/components/parameters/preferPost"
      requestBody:
        $ref: "#/components/requestBodies/messages"
      responses:
        "201":
          description: Created
    delete:
      tags:
        - messages
      parameters:
        - $ref: "#/components/parameters/rowFilter.messages.id"
        - $ref: "#/components/parameters/rowFilter.messages.treeId"
        - $ref: "#/components/parameters/rowFilter.messages.parent"
        - $ref: "#/components/parameters/rowFilter.messages.content"
        - $ref: "#/components/parameters/rowFilter.messages.role"
        - $ref: "#/components/parameters/rowFilter.messages.createdAt"
        - $ref: "#/components/parameters/rowFilter.messages.updatedAt"
        - $ref: "#/components/parameters/rowFilter.messages.comment"
        - $ref: "#/components/parameters/preferReturn"
      responses:
        "204":
          description: No Content
    patch:
      tags:
        - messages
      parameters:
        - $ref: "#/components/parameters/rowFilter.messages.id"
        - $ref: "#/components/parameters/rowFilter.messages.treeId"
        - $ref: "#/components/parameters/rowFilter.messages.parent"
        - $ref: "#/components/parameters/rowFilter.messages.content"
        - $ref: "#/components/parameters/rowFilter.messages.role"
        - $ref: "#/components/parameters/rowFilter.messages.createdAt"
        - $ref: "#/components/parameters/rowFilter.messages.updatedAt"
        - $ref: "#/components/parameters/rowFilter.messages.comment"
        - $ref: "#/components/parameters/preferReturn"
      requestBody:
        $ref: "#/components/requestBodies/messages"
      responses:
        "204":
          description: No Content
externalDocs:
  description: PostgREST Documentation
  url: https://postgrest.org/en/v10.2/api.html
servers:
  - url: http://localhost:3000
components:
  parameters:
    preferParams:
      name: Prefer
      description: Preference
      required: false
      in: header
      schema:
        type: string
        enum:
          - params=single-object
    preferReturn:
      name: Prefer
      description: Preference
      required: false
      in: header
      schema:
        type: string
        enum:
          - return=representation
          - return=minimal
          - return=none
    preferCount:
      name: Prefer
      description: Preference
      required: false
      in: header
      schema:
        type: string
        enum:
          - count=none
    preferPost:
      name: Prefer
      description: Preference
      required: false
      in: header
      schema:
        type: string
        enum:
          - return=representation
          - return=minimal
          - return=none
          - resolution=ignore-duplicates
          - resolution=merge-duplicates
    select:
      name: select
      description: Filtering Columns
      required: false
      in: query
      schema:
        type: string
    on_conflict:
      name: on_conflict
      description: On Conflict
      required: false
      in: query
      schema:
        type: string
    order:
      name: order
      description: Ordering
      required: false
      in: query
      schema:
        type: string
    range:
      name: Range
      description: Limiting and Pagination
      required: false
      in: header
      schema:
        type: string
    rangeUnit:
      name: Range-Unit
      description: Limiting and Pagination
      required: false
      in: header
      schema:
        type: string
        default: items
    offset:
      name: offset
      description: Limiting and Pagination
      required: false
      in: query
      schema:
        type: string
    limit:
      name: limit
      description: Limiting and Pagination
      required: false
      in: query
      schema:
        type: string
    rowFilter.trees.id:
      name: id
      required: false
      in: query
      schema:
        type: string
        format: uuid
    rowFilter.trees.name:
      name: name
      required: false
      in: query
      schema:
        type: string
        format: text
    rowFilter.trees.description:
      name: description
      required: false
      in: query
      schema:
        type: string
        format: text
    rowFilter.trees.userId:
      name: userId
      required: false
      in: query
      schema:
        type: string
        format: uuid
    rowFilter.trees.forks:
      name: forks
      required: false
      in: query
      schema:
        type: string
        format: integer
    rowFilter.trees.isPublic:
      name: isPublic
      required: false
      in: query
      schema:
        type: string
        format: boolean
    rowFilter.trees.createdAt:
      name: createdAt
      required: false
      in: query
      schema:
        type: string
        format: timestamp with time zone
    rowFilter.trees.updatedAt:
      name: updatedAt
      required: false
      in: query
      schema:
        type: string
        format: timestamp with time zone
    rowFilter.trees.forkSourceId:
      name: forkSourceId
      required: false
      in: query
      schema:
        type: string
        format: uuid
    rowFilter.trees.settings:
      name: settings
      required: false
      in: query
      schema:
        type: string
        format: jsonb
    rowFilter.trees.isTemplate:
      name: isTemplate
      required: false
      in: query
      schema:
        type: string
        format: boolean
    rowFilter.trees.templateId:
      name: templateId
      required: false
      in: query
      schema:
        type: string
        format: uuid
    rowFilter.messages.id:
      name: id
      required: false
      in: query
      schema:
        type: string
        format: uuid
    rowFilter.messages.treeId:
      name: treeId
      required: false
      in: query
      schema:
        type: string
        format: uuid
    rowFilter.messages.parent:
      name: parent
      required: false
      in: query
      schema:
        type: string
        format: uuid
    rowFilter.messages.content:
      name: content
      required: false
      in: query
      schema:
        type: string
        format: text
    rowFilter.messages.role:
      name: role
      required: false
      in: query
      schema:
        type: string
        format: text
    rowFilter.messages.createdAt:
      name: createdAt
      required: false
      in: query
      schema:
        type: string
        format: timestamp with time zone
    rowFilter.messages.updatedAt:
      name: updatedAt
      required: false
      in: query
      schema:
        type: string
        format: timestamp with time zone
    rowFilter.messages.comment:
      name: comment
      description: Extra user-provided information, not sent to LLM
      required: false
      in: query
      schema:
        type: string
        format: text
  requestBodies:
    trees:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/trees"
        application/vnd.pgrst.object+json:
          schema:
            $ref: "#/components/schemas/trees"
        text/csv:
          schema:
            $ref: "#/components/schemas/trees"
      description: trees
    messages:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/messages"
        application/vnd.pgrst.object+json:
          schema:
            $ref: "#/components/schemas/messages"
        text/csv:
          schema:
            $ref: "#/components/schemas/messages"
      description: messages
  schemas:
    trees:
      required:
        - id
        - userId
        - forks
        - isPublic
        - createdAt
        - updatedAt
        - isTemplate
      properties:
        id:
          default: gen_random_uuid()
          description: |-
            Note:
            This is a Primary Key.<pk/>
          format: uuid
          type: string
        name:
          format: text
          type: string
        description:
          format: text
          type: string
        userId:
          default: auth.uid()
          format: uuid
          type: string
        forks:
          default: 0
          format: integer
          type: integer
        isPublic:
          default: false
          format: boolean
          type: boolean
        createdAt:
          default: now()
          format: timestamp with time zone
          type: string
        updatedAt:
          default: now()
          format: timestamp with time zone
          type: string
        forkSourceId:
          description: |-
            Note:
            This is a Foreign Key to `trees.id`.<fk table='trees' column='id'/>
          format: uuid
          type: string
        settings:
          format: jsonb
        isTemplate:
          default: false
          format: boolean
          type: boolean
        templateId:
          description: |-
            Note:
            This is a Foreign Key to `trees.id`.<fk table='trees' column='id'/>
          format: uuid
          type: string
      type: object
    messages:
      required:
        - id
        - treeId
        - content
        - createdAt
        - updatedAt
      properties:
        id:
          default: gen_random_uuid()
          description: |-
            Note:
            This is a Primary Key.<pk/>
          format: uuid
          type: string
        treeId:
          description: |-
            Note:
            This is a Foreign Key to `trees.id`.<fk table='trees' column='id'/>
          format: uuid
          type: string
        parent:
          description: >-
            Note:

            This is a Foreign Key to `messages.id`.<fk table='messages' column='id'/>
          format: uuid
          type: string
        content:
          format: text
          type: string
        role:
          format: text
          type: string
        createdAt:
          default: now()
          format: timestamp with time zone
          type: string
        updatedAt:
          default: now()
          format: timestamp with time zone
          type: string
        comment:
          description: Extra user-provided information, not sent to LLM
          format: text
          type: string
      type: object
