import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

// This empty API service gets endpoints injected later with `injectEndpoints()`
// in igniteApi.ts generated by @rtk-query/codegen-openapi
export const api = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
  endpoints: () => ({}),
})
