name: Deploy

on:
  push:
    branches: ['main']

  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build:web
      - run: npm run generate:openapi && cp ignite-gpt-openapi/openapi.json ignite-gpt-app/dist/openapi.json
      - run: npm run build:docs && cp -R ignite-gpt-openapi/docs ignite-gpt-app/dist/
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'ignite-gpt-app/dist'
      - uses: actions/deploy-pages@v1
        id: deployment
